on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: |
          west init -l config
          west update
          west zephyr-export
          west build -s zmk/app -b seeeduino_xiao_ble -- -DSHIELD=roBa_L
